# Change these first
owner: gwanryo # Your GitHub username
repo: upptime # Your Github repository name

# Add your sites here
sites:
  - name: JMM.KR
    url: https://jmm.kr
    assignees:
      - gwanryo

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.jmm.kr
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Status
  introTitle: "JMM Status"
  introMessage: This page shows **real-time** status of the JMM website and API.
  navbar:
    - title: Status
      href: /
    - title: JMM
      href: https://jmm.kr
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
